language: java

before_install:
  - sudo apt-get update
  - sudo apt-get install php5-cli php5-curl php5-dev php-pear
  - yes n | sudo pecl install yar
  - echo 'date.timezone = "PRC"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo "extension=yar.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

before_script:
  - nohup php -S 127.0.0.1:8095 -t src/test/resources > /dev/null &

script:
  - mvn clean test package
