language: java

before_install:
  - sudo apt-get update
  - sudo apt-get install php php-pear
  - sudo pecl install yar

before_script:
  - nohup php -S 127.0.0.1:8095 -t src/test/resources > /dev/null &

script:
  - mvn clean test
