language: java

before_install:
  - sudo add-apt-repository -y ppa:ondrej/php5
  - sudo apt-get update
  - sudo apt-get install php5 php-pear
  - yes no | sudo pecl install yar

before_script:
  - php -ddate.timezone=PRC -dextension=yar.so -S 127.0.0.1:8095 -t src/test/resources 2>&1

script:
  - mvn clean test package

after_success:
  - mvn clean cobertura:cobertura coveralls:report