language: java

before_install:
  - sudo apt-get update
  - sudo apt-get install php5-cli php5-curl php5-dev php-pear
  - yes n | sudo pecl install yar

before_script:
  - nohup php -ddate.timezone=PRC -dextension=yar.so -S 127.0.0.1:8095 -t src/test/resources > /dev/null &

script:
  - sh -c 'nohup php -ddate.timezone=PRC -dextension=yar.so -S 127.0.0.1:8095 -t src/test/resources > /dev/null &' && mvn clean test package

after_success:
  - mvn clean cobertura:cobertura coveralls:report